### ISSUE TITLE
Update serialport dependency

### ISSUE THREAD

**Issue by achingbrain** [omcaree/node-pololumaestro#1]
It seems serialport needs to be > 1.1.1 to work with node 0.10.x ( https://github.com/voodootikigod/node-serialport/issues/172 ) but node-pololumaestro has it pinned at 1.0.6.

Any chance of increasing the dependency version?  The latest available is 1.1.3.

**Comment by omcaree** [comment]
Thanks for pointing this out, I've only just recently moved to 0.10.x myself and not yet used this module.

I seem to recall the reason for the 1.0.6 dependency was because the latest version at the time (1.0.7?) didn't work correctly. 

I have just tested with 1.1.3 and all is well, so I have removed the version dependency altogether. I have also added a ready event (example code has been updated). This has been tested with node v0.10.9 on Linux and works fine.
